package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlunoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunoAllPropertiesEquals(Aluno expected, Aluno actual) {
        assertAlunoAutoGeneratedPropertiesEquals(expected, actual);
        assertAlunoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunoAllUpdatablePropertiesEquals(Aluno expected, Aluno actual) {
        assertAlunoUpdatableFieldsEquals(expected, actual);
        assertAlunoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunoAutoGeneratedPropertiesEquals(Aluno expected, Aluno actual) {
        assertThat(expected)
            .as("Verify Aluno auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunoUpdatableFieldsEquals(Aluno expected, Aluno actual) {
        assertThat(expected)
            .as("Verify Aluno relevant properties")
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlunoUpdatableRelationshipsEquals(Aluno expected, Aluno actual) {
        // empty method
    }
}
